<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Intl\Intl;
use Skaphandrus\AppBundle\Utils\Utils;

/**
 * SkCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkBusinessRepository extends EntityRepository {

    public function findBySlug($country,$location, $slug, $locale) {
        $name = Utils::unslugify($slug);
        $location = $this->getEntityManager()->getRepository('SkaphandrusAppBundle:SkLocation')
                ->findBySlug($location, $country, $locale);

        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT b
                FROM SkaphandrusAppBundle:SkBusiness b
                JOIN b.address a
                JOIN a.location l
                JOIN l.region r
                WHERE REPLACE(REPLACE(b.name, \'_\', \'/\'), \'-\', \' \') = :name
                AND IDENTITY(a.location) = :location_id')
                ->setParameter('name', $name)
                ->setParameter('location_id', $location->getId());
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findAllJoinLanguagesAndCurrencies_Old() {
        return $this->getEntityManager()->createQuery(
                        'SELECT b, l, c
            FROM SkaphandrusAppBundle:SkBusiness b
            Left JOIN b.language l
            Left join b.currency c'
                )->getResult();
    }

    
     public function findAllWithAddress() {
        return $this->getEntityManager()->createQuery(
                        'SELECT b, a, l, r, c
            FROM SkaphandrusAppBundle:SkBusiness b
            JOIN b.address a
            JOIN a.location l
            JOIN l.region r
            JOIN r.country c'
                )->getResult();
    }
    
    
    
    public function findAllBusiness3($locale) {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = "SELECT b.id as id, b.name as name, lt.name as location_name, c.name as country_name
                FROM sk_business as b
                LEFT JOIN sk_address as a on b.id = a.business_id
                JOIN sk_location as l on a.location_id = l.id
                JOIN sk_location_translation as lt on l.id = lt.translatable_id
                JOIN sk_region as r on r.id = l.region_id
                JOIN sk_country as c on c.id = r.country_id
                where lt.locale = '" . $locale . "'
                order by name asc";
        
        $statement = $connection->prepare($sql);
        $statement->execute();
        $values = $statement->fetchAll();
        $result = array();

        foreach ($values as $value) {
            $business = new \Skaphandrus\AppBundle\Entity\SkBusiness();
            $business->setId($value['id']);
            $business->setName($value['name']);
            
            $country = new \Skaphandrus\AppBundle\Entity\SkCountry();
            $country->setName($value['country_name']);
            
            $region = new \Skaphandrus\AppBundle\Entity\SkRegion();
            $region->setCountry($country);
            
            $location = new \Skaphandrus\AppBundle\Entity\SkLocation();
            $location->translate($locale)->setName($value['location_name']);
            $location->setRegion($region);
            
            $address = new \Skaphandrus\AppBundle\Entity\SkAddress();
            $address->setLocation($location);
            
            $business->setAddress($address);

            $result[] = $business;
        }

        return $result;
    }

    public function findAllBusiness($locale) {
        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = "SELECT b.id as id, b.name as name, lt.name as location_name, c.name as country_name
                FROM sk_business as b
                LEFT JOIN sk_address as a on b.id = a.business_id
                JOIN sk_location as l on a.location_id = l.id
                JOIN sk_location_translation as lt on l.id = lt.translatable_id
                JOIN sk_region as r on r.id = l.region_id
                JOIN sk_country as c on c.id = r.country_id
                where lt.locale = '" . $locale . "'
                order by name asc";

        $statement = $connection->prepare($sql);
        $statement->execute();
        $values = $statement->fetchAll();

        return $values;
    }

}
