<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkClassRepository extends EntityRepository {

  public function findLikeName($term) {
        return $this->getEntityManager()->createQuery(
          "SELECT c
          FROM SkaphandrusAppBundle:SkClass c
          WHERE c.name LIKE :term
          ORDER BY c.name DESC"
        )->setParameter('term', '%' . $term . '%')->getResult();
    }

}
