<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkCountryRepository extends EntityRepository
{
  // public function findOneByName($name) {
  //   return $this->getEntityManager()
  //     ->createQuery(
  //       "SELECT c
  //       FROM SkaphandrusAppBundle:SkCountry c
  //       JOIN SkaphandrusAppBundle:SkCountryTranslation ct
  //         WITH c.id = ct.translatable_id
  //       WHERE ct.name = :name"
  //     )->setParameter('name', $name)->getSingleResult();
  // }
}
