<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkFamilyRepository extends EntityRepository {

  public function findLikeName($term) {
    return $this->getEntityManager()->createQuery(
      "SELECT f
      FROM SkaphandrusAppBundle:SkFamily f
      WHERE f.name LIKE :term
      ORDER BY f.name DESC"
    )->setParameter('term', '%' . $term . '%')->getResult();
  }
}
