<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkGenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkGenusRepository extends EntityRepository {

  public function findLikeName($term) {
    return $this->getEntityManager()->createQuery(
      "SELECT g
      FROM SkaphandrusAppBundle:SkGenus g
      WHERE g.name LIKE :term
      ORDER BY g.name DESC"
    )->setParameter('term', '%' . $term . '%')->getResult();
  }
}
