<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkKeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkKeywordRepository extends EntityRepository {

    public function findLikeKeyword($keyword) {
        $query = $this->getEntityManager()->createQuery(
            'SELECT k
            FROM SkaphandrusAppBundle:SkKeyword k
            WHERE k.keyword LIKE :keyword'
        )->setParameter('keyword', $keyword);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
