<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkKingdomRepository extends EntityRepository {

    public function findLikeName($term) {
        return $this->getEntityManager()->createQuery(
                        "SELECT k
          FROM SkaphandrusAppBundle:SkKingdom k
          WHERE k.name LIKE :term
          ORDER BY k.name DESC"
                )->setParameter('term', '%' . $term . '%')->getResult();
    }

 public function getSpecies($kingdom_id) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT s 
                FROM SkaphandrusAppBundle:SkSpecies s
                JOIN s.genus g
                JOIN g.family f
                JOIN f.order o
                JOIN o.class c
                JOIN c.phylum p
                JOIN p.kingdom k
                WHERE k.id = :kingdom_id'
                        )->setParameter('kingdom_id', $kingdom_id)->getResult();
    }

}
