<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkOrderRepository extends EntityRepository {

  public function findLikeName($term) {
    return $this->getEntityManager()->createQuery(
      "SELECT o
      FROM SkaphandrusAppBundle:SkOrder o
      WHERE o.name LIKE :term
      ORDER BY o.name DESC"
    )->setParameter('term', '%' . $term . '%')->getResult();
  }
  
  
  public function getSpecies($order_id) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT s 
                FROM SkaphandrusAppBundle:SkSpecies s
                JOIN s.genus g
                JOIN g.family f
                JOIN f.order o
                WHERE o.id = :order_id'
                        )->setParameter('order_id', $order_id)->getResult();
    }
}
