<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkOrderRepository extends EntityRepository {

  public function findLikeName($term) {
    return $this->getEntityManager()->createQuery(
      "SELECT o
      FROM SkaphandrusAppBundle:SkOrder o
      WHERE o.name LIKE :term
      ORDER BY o.name DESC"
    )->setParameter('term', '%' . $term . '%')->getResult();
  }
}
