<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * SkPhotoContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhotoContestSponsorRepository extends EntityRepository {

    public function findSponsorsByContest($contest) {
        
//        $sponsors = $this->getEntityManager()->createQuery(
//            'SELECT DISTINCT s
//            FROM SkaphandrusAppBundle:SkPhotoContestSponsor s
//            INNER JOIN SkaphandrusAppBundle:SkPhotoContestAward a
//            WHERE a.contest = :contest_id'
//        )->setParameter('contest_id', $contest)->getResult();
    
        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('SkaphandrusAppBundle:SkPhotoContestSponsor', 's');
        $rsm->addFieldResult('s', 'id', 'id');
        $rsm->addFieldResult('s', 'name', 'name');

        $query = $this->getEntityManager()->createNativeQuery( 
                'SELECT distinct s.*
                    FROM sk_photo_contest_sponsor s
                    INNER JOIN sk_photo_contest_award_sponsor spon 
                    ON s.id = spon.sponsor_id
                    INNER JOIN sk_photo_contest_award a 
                    ON a.id = spon.award_id
                    WHERE a.contest_id = ?', $rsm);
        

        $query->setParameter(1, $contest);
     
        $sponsors = $query->getResult();
        
        return $sponsors;
  
    }

}
