<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkPhylumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhylumRepository extends EntityRepository {

  public function findLikeName($term) {
        return $this->getEntityManager()->createQuery(
          "SELECT p
          FROM SkaphandrusAppBundle:SkPhylum p
          WHERE p.name LIKE :term
          ORDER BY p.name DESC"
        )->setParameter('term', '%' . $term . '%')->getResult();
    }

}
