<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * SkPhotoContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhotoContestJudgeRepository extends EntityRepository {

    public function findJudgesByContest($contest) {

//        $rsm = new ResultSetMapping();
//        $rsm->addEntityResult('SkaphandrusAppBundle:SkPersonal', 'p');
//        $rsm->addFieldResult('p', 'id', 'id');
//        $rsm->addFieldResult('p', 'firstname', 'firstname');
//        
//        $query = $this->getEntityManager()->createNativeQuery( 
//                'SELECT distinct p.*
//                    FROM skaphandrus4.sk_personal p
//                    INNER JOIN skaphandrus4.fos_user fu 
//                    ON p.fos_user_id = fu.id
//                    INNER JOIN skaphandrus4.sk_photo_contest_judge j 
//                    ON fu.id = j.fos_user_id
//                    INNER JOIN skaphandrus4.sk_photo_contest_judge_award judgeAwd
//                    ON j.id = judgeAwd.judge_id
//                    INNER JOIN sk_photo_contest_award a 
//                    ON a.id = judgeAwd.award_id
//                    WHERE a.contest_id = ?', $rsm);

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('SkaphandrusAppBundle:SkPhotoContestJudge', 'j');
        $rsm->addEntityResult('SkaphandrusAppBundle:FosUser', 'f');
        $rsm->addFieldResult('j', 'id', 'id');
        $rsm->addFieldResult('f', 'id', 'id');


        $query = $this->getEntityManager()->createNativeQuery(
                'SELECT j.id, f.id 
                    FROM fos_user f
                    INNER JOIN sk_photo_contest_judge j
                    ON f.id = j.fos_user_id
                    INNER JOIN sk_photo_contest_judge_award judgeAwd 
                    ON j.id = judgeAwd.judge_id
                    INNER JOIN sk_photo_contest_award a 
                    ON a.id = judgeAwd.award_id
                    WHERE a.contest_id = ?', $rsm);

        $query->setParameter(1, $contest);

        $judges = $query->getResult();

        return $judges;
    }

}
