<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Skaphandrus\AppBundle\Utils\Utils;

/**
 * SkPhotoContestCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhotoContestCategoryJudgeVotation extends EntityRepository {

    public function findPhotos($category_id) {

        $em = $this->getEntityManager();
        $connection = $em->getConnection();

//        $sql = "SELECT *
//                FROM sk_photo_contest_category_photo
//                where category_id =". $category_id ;
//        $sql = "SELECT * 
//                FROM sk_photo_contest_category_judge_votation as jv
//                join sk_photo_contest_category_judge_photo_vote as jpv on jv.id = jpv.votation_id
//                where category_id =2";
       $sql = " SELECT v.fos_user_id as f, v.category_id as c, v.photo_id as p,
                count(v.photo_id) as countable, photo.title as t
                FROM sk_photo_contest_vote as v
                join sk_photo as photo on photo.id = v.photo_id
                where category_id = ". $category_id ."
                group by v.photo_id
                order by countable desc ";

        $statement = $connection->prepare($sql);
        $statement->execute();
        $values = $statement->fetchAll();

        return $values;
    }

}
