<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkPhotoContestCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhotoContestCategoryRepository extends EntityRepository {

    public function findOneBySlug($slug, $locale) {
        $name = str_replace('-', ' ', $slug);

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT cc
                FROM SkaphandrusAppBundle:SkPhotoContestCategory cc
                JOIN cc.translations t
                WHERE t.name = :name
                AND t.locale = :locale'
                )->setParameter('name', $name)->setParameter('locale', $locale);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
