<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkPhotoContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhotoContestRepository extends EntityRepository {

    public function findUsers($contest) {
        $categories = $contest->getCategories();
        $users = array();
        
        foreach ($categories as $category) {
            foreach ($category->getPhoto() as $photo) {
                $user = $photo->getFosUser();

                if ($user && !array_key_exists($user->getId(), $users)) {
                    $users[$user->getId()] = $user;
                }
            }
        }

        return $users;
    }
}
