<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Skaphandrus\AppBundle\Utils\Utils;

/**
 * SkPhotoContestCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhotoContestCategoryJudgeVotationRepository extends EntityRepository {

    public function findMostVotedPhotosByCategory($category_id) {

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $sql = " SELECT v.photo_id as id, count(v.photo_id) as countable
                FROM sk_photo_contest_vote as v
                where v.category_id = " . $category_id . "
                group by v.photo_id
                order by countable desc ";

        $statement = $connection->prepare($sql);
        $statement->execute();
        $photos = $statement->fetchAll();

        return $photos;
    }

    public function getJudgeVotationsByContest($contest_id, $judge) {

        return $this->getEntityManager()->createQuery(
                        'SELECT v
            FROM SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation v
            JOIN SkaphandrusAppBundle:SkPhotoContestCategory c with c.id = v.category
            WHERE c.contest = :contest AND v.judge = :judge'
                )->setParameter('contest', $contest_id)->setParameter('judge', $judge->getId())->getResult();
    }

    public function findContestByVotation($votation_id) {

        return $this->getEntityManager()->createQuery(
                        'SELECT c
            FROM SkaphandrusAppBundle:SkPhotoContest c
            JOIN SkaphandrusAppBundle:SkPhotoContestCategory cc with c.id = cc.contest
            JOIN SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation v with cc.id = v.category
            WHERE v.id = :votation '
                )->setParameter('votation', $votation_id)->getSingleResult();
    }

}
