<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SkPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPhotoRepository extends EntityRepository
{
    public function findPhotosCountByUserForModel($id, $model = 'species') {
        return $this->getEntityManager()
            ->createQuery(
            "SELECT u, COUNT(p.id) as countable
            FROM SkaphandrusAppBundle:FosUser u
            JOIN SkaphandrusAppBundle:SkPhoto p
                WITH u.id = IDENTITY(p.fosUser)
            WHERE IDENTITY(p.$model) = :id
            GROUP BY u.id
            ORDER BY countable DESC"
            )->setParameter('id', $id)->getResult();
    }

    public function findAllAsPaginator($page, $per_page = 10, $params = array()) {
        $first = ($page - 1) * $per_page;

        // $query = $this->getEntityManager()
        //     ->createQuery("SELECT p FROM SkaphandrusAppBundle:SkPhoto p ORDER BY p.createdAt DESC")
        //     ->setFirstResult($first)
        //     ->setMaxResults($per_page);
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p')
           ->from('SkaphandrusAppBundle:SkPhoto', 'p')
           ->setParameters($params)
           ->setFirstResult($first)
           ->setMaxResults($per_page)
           ->getQuery();

        return new Paginator($qb, TRUE);
    }

    
    public function getPrimaryPhotoForSpecies($species_id) {
        
        return $this->findBy(array('species' => $species_id), array('id' => 'DESC'))[0];
    }
    
    
    
}
