<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkPointsExtraRepository extends EntityRepository {

    //usado na pagina points
    public function getPointsFromContest($fos_user, $points_type) {

        $em = $this->getEntityManager();
        $connection = $em->getConnection();

        $sql = "SELECT points_extra
                FROM skaphandrus4.sk_points_extra 
                where fos_user_id =" . $fos_user . " and points_type_id = " . $points_type;

        $statement = $connection->prepare($sql);
        $statement->execute();
        $values = $statement->fetchColumn();

        return $values;
    }

}
