<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkRegionRepository extends EntityRepository {

    public function findLikeName($term, $locale) {

        return $this->getEntityManager()->createQuery(
                        "SELECT r
                    FROM SkaphandrusAppBundle:SkRegion r
                    JOIN r.translations t
                    WHERE t.name LIKE :term
                    AND t.locale = :locale
                    ORDER BY t.name DESC"
                )->setParameter('term', '%' . $term . '%')->setParameter('locale', $locale)->getResult();
    }

    public function findRegionsJoinTranslations($country_id, $locale) {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT r, t
                FROM SkaphandrusAppBundle:SkRegion r JOIN r.translations t
                WHERE t.locale =:locale AND r.country =:country_id
                ')
                        ->setParameter('locale', $locale)
                        ->setParameter('country_id', $country_id)->getResult();
    }

}
