<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkSpotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkSpotRepository extends EntityRepository {

    // public function findOneBySlugJoinedToTranslation($name, $locale) {
    //     $query = $this->getEntityManager()
    //         ->createQuery(
    //             'SELECT s, t
    //             FROM SkaphandrusAppBundle:SkSpot s
    //             JOIN s.translations t
    //             WHERE t.name = :name
    //             AND t.locale = :locale'
    //             )->setParameter('name', $name)->setParameter('locale', $locale);
    //     try {
    //         return $query->getSingleResult();
    //     } catch (\Doctrine\ORM\NoResultException $e) {
    //         return null;
    //     }
    // }

    
    
        public function findLikeName($term, $locale) {


        return $this->getEntityManager()->createQuery(
                "SELECT s, l
                FROM SkaphandrusAppBundle:SkSpot s
                JOIN s.translations t
                JOIN s.location l
         WHERE t.name LIKE :term
         AND t.locale = :locale
        ORDER BY t.name DESC"
                )->setParameter('term', '%' . $term . '%')->setParameter('locale', $locale)->getResult();
        
        
        
        
        
        
        
    }
    
    
    
    
    
    public function findBySlug($slug, $location, $country, $locale) {
        $name = str_replace('-', ' ', $slug);

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT s
                FROM SkaphandrusAppBundle:SkSpot s
                JOIN s.translations t
                JOIN s.location l
                WHERE t.name = :name
                AND t.locale = :locale
                AND IDENTITY(s.location) = ' . $this->getEntityManager()->getRepository('SkaphandrusAppBundle:SkLocation')->findBySlug($location, $country, $locale)->getId()
                )->setParameter('name', $name)->setParameter('locale', $locale);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
