<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkSpotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkSpotRepository extends EntityRepository {

//  public function findOneByName($name) {
//    return $this->getEntityManager()
//      ->createQuery(
//        "SELECT s
//        FROM SkaphandrusAppBundle:SkSpot s
//        JOIN SkaphandrusAppBundle:SkSpotTranslation st
//          WITH s.id = st.translatable_id
//        WHERE st.name = :name"
//      )->setParameter('name', $name)->getSingleResult();
//  }

    public function findOneBySlugJoinedToTranslation($name) {
        $query = $this->getEntityManager()
                        ->createQuery(
                                'SELECT s, t FROM SkaphandrusAppBundle:SkSpot s
             JOIN s.translations t
             WHERE t.name = :name
             AND t.locale = :locale'
                        )->setParameter('name', $name)->setParameter('locale', 'en');
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
