<?php

namespace Skaphandrus\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * SkPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkUserPointsRepository extends EntityRepository {

    //1ª fotografia associada (e validada) de espécie (campo created_at + 3 validações)(5 PONTOS)
//    public function findFirstPhotosFromSpecies($user_id) {
//        return $this->getEntityManager()
//                        ->createQuery(
//                                "SELECT u, COUNT(p.id) as countable
//            FROM SkaphandrusAppBundle:FosUser u
//            JOIN SkaphandrusAppBundle:SkPhoto p
//                WITH u.id = IDENTITY(p.fosUser)
//            WHERE IDENTITY(p.$model) = :id
//            GROUP BY u.id
//            ORDER BY countable DESC"
//                        )->setParameter('id', $id)->getResult();
//    }


    public function findFirstPhotosFromSpecies($user_id) {


        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare("SELECT sk_photo.* FROM sk_photo INNER JOIN ( 
    SELECT id, species_id, MIN(created_at) AS first_photo FROM sk_photo GROUP BY species_id ) first_record ON sk_photo.id = first_record.id 
WHERE sk_photo.fos_user_id = :user_id ");
        $statement->bindValue('user_id', $user_id);
        $statement->execute();
        $results = $statement->fetchAll();

        return $results;
    }

}
