imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }
    - { resource: @SkaphandrusAppBundle/Resources/config/admin.xml }


framework:
    #esi:             ~
    #translator:      { fallback: [pt] }
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
#        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'SkaphandrusAppBundle:Form:fields.html.twig'

#    form:
#        resources:
#            - 'CmfMediaBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "SkaphandrusAppBundle", "FOSCommentBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
#        types:
#            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    SkaphandrusAppBundle: ~
                    LexikTranslationBundle: ~
                dql:
                    string_functions:
                        replace: Skaphandrus\AppBundle\DQL\ReplaceFunction
        auto_generate_proxy_classes: "%kernel.debug%"
#        auto_mapping: true
        

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    # host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)


a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [en, pt]          # [1-a]
    default_locale: en             # [1-b]
    required_locales: [en]         # [1-c]
    manager_registry: doctrine      # [2]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [3]


security:
    # [...]
    acl:
        connection: default
    encoders:
    # default values for FOSUserBundle (Symfony2)
    # see http://symfony.com/doc/current/reference/configuration/security.html
        default:
          algorithm: sha512
          iterations: 5000
          encode_as_base64: true
        # legacy encoder used by sfGuard (symfony 1)
        legacy:
          algorithm: sha1
          iterations: 1
          encode_as_base64: false    



fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Skaphandrus\AppBundle\Entity\FosUser
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address:     support-noreply@skaphandrus.com
        sender_name: Skaphandrus
    registration:
        confirmation:
            enabled:  true
            template: SkaphandrusAppBundle:FOSUserEmail:register.html.twig
        form:
            type: skaphandrus_user_registration
    resetting:
        email:
            template: SkaphandrusAppBundle:FOSUserEmail:resetting.html.twig
        form:
            type: skaphandrus_user_resetting


    #group:
        #group_class:   Application\Sonata\UserBundle\Entity\Group
        #group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

#    service:
#        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
#
#    profile:
#        # Authentication Form
#        form:
#            type:               fos_user_profile
#            handler:            fos_user.profile.form.handler.default
#            name:               fos_user_profile_form
#            validation_groups:  [Authentication] # Please note : this is not the default value


#@LM - por causa dos dois tipos de encoding
parameters:
    security.encoder.digest.class: Skaphandrus\AppBundle\Security\MessageDigestPasswordEncoder


sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

    templates:
        form:
            - SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig
                currency:   SonataAdminBundle:CRUD:list_currency.html.twig
                percent:    SonataAdminBundle:CRUD:list_percent.html.twig
                choice:     SonataAdminBundle:CRUD:list_choice.html.twig
                url:        SonataAdminBundle:CRUD:list_url.html.twig

            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig
                currency:   SonataAdminBundle:CRUD:base_currency.html.twig
                percent:    SonataAdminBundle:CRUD:base_percent.html.twig
                choice:     SonataAdminBundle:CRUD:show_choice.html.twig
                url:        SonataAdminBundle:CRUD:show_url.html.twig

lexik_translation:
    fallback_locale: en      # (required) default locale to use
    managed_locales: [en, pt]    # (required) locales that the bundle have to manage



#      "square"     =>  "_s  => 75px*75px",
#      "thumbnail"  =>  "_t  => 100px do lado maior",
#      "small"      =>  "_m  => 240px do lado maior",
#      "medium"     =>  "    => 500px do lado maior",
#      "medium_640" =>  "_z  => 640px do lado maior",
#      "large"      =>  "_b  =>1024px do lado maior",
#      "original"   =>  "_o"



#http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        
        small_thumb:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
                
        sk_widen_50:
            filters:
                relative_resize: { widen: 50 } 
        sk_widen_75:
            filters:
                relative_resize: { widen: 75 } # Transforms 500x400 to 260x??
        sk_widen_100:
            filters:
                relative_resize: { widen: 100 }
        sk_widen_160:
            filters:
                relative_resize: { widen: 160 }
        sk_widen_240:
            filters:
                relative_resize: { widen: 240 }
        
        #galeria de fotografias das categorias dos concursos
        sk_widen_265:
            filters:
                relative_resize: { widen: 265 }
                
        #galeria de fotografias        
        sk_widen_400:
            filters:
                relative_resize: { widen: 400 } 
        sk_widen_590:
            filters:
                relative_resize: { widen: 590 }
                
        #single contest banner image
        sk_crop_900:
            filters:
                thumbnail: { size: [900, 300] , mode: outbound }
        
        #destinations page imagem grande
        sk_crop_555:
            filters:
                thumbnail: { size: [555, 270] , mode: outbound }                
        #destinations page imagem pequena
        sk_crop_272:
            filters:
                thumbnail: { size: [272, 270] , mode: outbound }   
                
        #species page big image
        sk_crop_476:
            filters:
                thumbnail: { size: [476, 300] , mode: outbound }
                
        #species page small images        
        sk_crop_238:
            filters:
                thumbnail: { size: [238, 150] , mode: outbound }         
                
                
        sk_thumbnail_outbound_30:
            filters:
                thumbnail: { size: [30, 30], mode: outbound }
        sk_thumbnail_outbound_48:
            filters:
                thumbnail: { size: [48, 48], mode: outbound }
        sk_thumbnail_outbound_50:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

        # skGrid e associar a categoria no concurso
        sk_thumbnail_outbound_100:
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
        sk_thumbnail_outbound_110:
            filters:
                thumbnail: { size: [110, 110], mode: outbound }
        sk_thumbnail_outbound_130:
            filters:
                thumbnail: { size: [130, 130], mode: outbound }
        sk_thumbnail_outbound_200:
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                
        sk_thumbnail_outbound_198_100:
            filters:
                thumbnail: { size: [198, 100], mode: outbound }
        sk_upscale_800_600:
            filters:
                upscale: { min: [800, 600] }
                
        #for photo page
        sk_downscale_800_600:
            quality: 100
            filters:
                thumbnail: { size: [800, 600], mode: inset }
                
        #for ocean life id modules page
        sk_downscale_600_400:
            quality: 100
            filters:
                thumbnail: { size: [600, 400], mode: inset }

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Skaphandrus\AppBundle\Entity\Comment
            thread: Skaphandrus\AppBundle\Entity\Thread
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_FULLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ADMIN_USER
            delete: ADMIN_USER
        thread:
            create: IS_AUTHENTICATED_FULLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ADMIN_USER
            delete: ADMIN_USER
        vote:
            create: IS_AUTHENTICATED_FULLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ADMIN_USER
            delete: ADMIN_USER


#https://github.com/KnpLabs/KnpPaginatorBundle
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        #pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_message:
    db_driver: orm
    thread_class: Skaphandrus\AppBundle\Entity\FosMessageThread
    message_class: Skaphandrus\AppBundle\Entity\FosMessage
    new_thread_form:
        type: skaphandrus_message.new_thread.form.type
        
        
# app/config/config.yml
vich_uploader:
    db_driver: orm
    twig:       true
    mappings:
        contest_image:
            uri_prefix:         /uploads/contests
            upload_destination: %kernel.root_dir%/../web/uploads/contests
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        contest_sponsor_image:
            uri_prefix:         /uploads/contests
            upload_destination: %kernel.root_dir%/../web/uploads/contests
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        contest_award_image:
            uri_prefix:         /uploads/contests
            upload_destination: %kernel.root_dir%/../web/uploads/contests
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        photo:
            uri_prefix:         /uploads/fotografias
            upload_destination: %kernel.root_dir%/../web/uploads/fotografias
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        photo_user:
            uri_prefix:         /uploads/utilizadores
            upload_destination: %kernel.root_dir%/../web/uploads/utilizadores
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        module_photo:
            uri_prefix:         /uploads/characters
            upload_destination: %kernel.root_dir%/../web/uploads/characters
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        criteria_photo:
            uri_prefix:         /uploads/characters
            upload_destination: %kernel.root_dir%/../web/uploads/characters
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        business_photo:
            uri_prefix:         /uploads/business
            upload_destination: %kernel.root_dir%/../web/uploads/business
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        course_affiliation_photo:
            uri_prefix:         /uploads/course_affiliation
            upload_destination: %kernel.root_dir%/../web/uploads/course_affiliation
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
            
be_simple_i18n_routing: ~