#skaphandrus_madeira:
#    resource: "@SkaphandrusMadeiraBundle/Resources/config/routing.yml"
#    host:     "hello.example.com"




skaphandrus_app:
    resource: "@SkaphandrusAppBundle/Resources/config/routing.yml"
    prefix:   /


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


# FOS User bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

fos_user_profile_show:
    pattern: /profile/
    defaults: { _controller: FrameworkBundle:Redirect:urlRedirect, path: '/', permanent: true }

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translations

#cmf_media_file:
#    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"
#
#cmf_media_image:
#    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# Import FOSCommentBundle Configuration
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

# Import FOSMessageBundle Configuration
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /{_locale}/message_admin


i18nroute:
    resource: "@SkaphandrusAppBundle/Resources/config/i18n.yml"
    type: be_simple_i18n
    prefix:   /
    
    