skaphandrus_app:
    resource: "@SkaphandrusAppBundle/Resources/config/routing.yml"
    prefix:   /


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
    
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translations