skaphandrus_app:
    resource: "@SkaphandrusAppBundle/Resources/config/routing.yml"
    prefix:   /


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
    
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translations
    
#cmf_media_file:
#    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"
#
#cmf_media_image:
#    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"