business_admin:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:index" }

business_admin_show:
    path:     /{id}/show
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:show" }

business_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:new" }

business_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:create" }
    methods:  POST

business_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:edit" }

business_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:update" }
    methods:  [POST, PUT]

business_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:delete" }
    methods:  [POST, DELETE]


business_admin_create_currencies:
    path:     /createCurrencies
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:createCurrencies" }
    
business_admin_create_language:
    path:     /createLanguage
    defaults: { _controller: "SkaphandrusAppBundle:SkBusiness:createLanguages" }
