contest_request:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkContestRequest:index" }

contest_request_show:
    path:     /{id}/show
    defaults: { _controller: "SkaphandrusAppBundle:SkContestRequest:show" }

contest_request_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkContestRequest:new" }

contest_request_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkContestRequest:create" }
    methods:  POST

contest_request_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkContestRequest:edit" }

contest_request_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkContestRequest:update" }
    methods:  [POST, PUT]

contest_request_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkContestRequest:delete" }
    methods:  [POST, DELETE]
