identification_species_admin:
    path:     /{module_id}
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationSpecies:index", module_id: 6 }

identification_species_admin_show:
    path:     /{id}/show
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationSpecies:show" }

identification_species_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationSpecies:new" }

identification_species_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationSpecies:create" }
    methods:  POST

identification_species_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationSpecies:edit" }

identification_species_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationSpecies:update" }
    methods:  [POST, PUT]

identification_species_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationSpecies:delete" }
    methods:  [POST, DELETE]
