identification_group_admin:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationGroup:index" }

identification_group_admin_show:
    path:     /{id}/show
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationGroup:show" }

identification_group_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationGroup:new" }

identification_group_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationGroup:create" }
    methods:  POST

identification_group_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationGroup:edit" }

identification_group_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationGroup:update" }
    methods:  [POST, PUT]

identification_group_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkIdentificationGroup:delete" }
    methods:  [POST, DELETE]
