photo_contest_award_admin:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestAward:index" }

#photo_contest_award_admin_show:
#    path:     /{id}/show
#    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestAward:show" }

photo_contest_award_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestAward:new" }

photo_contest_award_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestAward:create" }
    methods:  POST

photo_contest_award_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestAward:edit" }

photo_contest_award_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestAward:update" }
    methods:  [POST, PUT]

photo_contest_award_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestAward:delete" }
    methods:  [POST, DELETE]
