judge_votation_admin:
    path:     /{contest_id}
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation:index" }

judge_votation_admin_show:
    path:     /{id}/show
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation:show" }

judge_votation_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation:new" }

judge_votation_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation:create" }
    methods:  POST

judge_votation_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation:edit" }

judge_votation_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation:update" }
    methods:  [POST, PUT]

judge_votation_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeVotation:delete" }
    methods:  [POST, DELETE]
