photo_contest_category_admin:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategory:index" }

#photo_contest_category_admin_show:
#    path:     /{id}/show
#    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategory:show" }

photo_contest_category_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategory:new" }

photo_contest_category_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategory:create" }
    methods:  POST

photo_contest_category_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategory:edit" }

photo_contest_category_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategory:update" }
    methods:  [POST, PUT]

photo_contest_category_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategory:delete" }
    methods:  [POST, DELETE]
