#judge_result_admin_teste:
#    path:     /
#    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:index2" }


judge_result_admin:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:index" }

judge_result_admin_show:
    path:     /{id}/show
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:show" }

judge_result_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:new" }

judge_result_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:create" }
    methods:  POST

judge_result_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:edit" }

judge_result_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:update" }
    methods:  [POST, PUT]

judge_result_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkPhotoContestCategoryJudgeResult:delete" }
    methods:  [POST, DELETE]
