region_admin:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkRegion:index" }

region_admin_show:
    path:     /{id}/show
    defaults: { _controller: "SkaphandrusAppBundle:SkRegion:show" }

region_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkRegion:new" }

region_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkRegion:create" }
    methods:  POST

region_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkRegion:edit" }

region_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkRegion:update" }
    methods:  [POST, PUT]

region_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkRegion:delete" }
    methods:  [POST, DELETE]
