spot_admin:
    path:     /
    defaults: { _controller: "SkaphandrusAppBundle:SkSpot:index" }

#spot_admin_show:
#    path:     /{id}/show
#    defaults: { _controller: "SkaphandrusAppBundle:SkSpot:show" }

spot_admin_new:
    path:     /new
    defaults: { _controller: "SkaphandrusAppBundle:SkSpot:new" }

spot_admin_create:
    path:     /create
    defaults: { _controller: "SkaphandrusAppBundle:SkSpot:create" }
    methods:  POST

spot_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SkaphandrusAppBundle:SkSpot:edit" }

spot_admin_update:
    path:     /{id}/update
    defaults: { _controller: "SkaphandrusAppBundle:SkSpot:update" }
    methods:  [POST, PUT]

spot_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SkaphandrusAppBundle:SkSpot:delete" }
    methods:  [POST, DELETE]
