################################################################################
### TRANSVERSAL
################################################################################
index:
    locales:  { en: "/", pt: "/pt" }
    defaults: { _controller: SkaphandrusAppBundle:Default:index }

destinations:
    locales:  { en: "/en/scuba-diving-sites", pt: "/pt/spots-mergulho" }
    defaults: { _controller: SkaphandrusAppBundle:Default:destinations }

modules:
    locales:  { en: "/en/ocean-life-identification", pt: "/pt/identificacao-vida-oceanos" }
    defaults: { _controller: SkaphandrusAppBundle:Identification:modules }

criterias:
    locales:  { en: "/en/ocean-life-identification/{slug}", pt: "/pt/identificacao-vida-oceanos/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Identification:criterias }

species:
    locales:  { en: "/en/marine-animals/species/{slug}", pt: "/pt/animais-marinhos/especie/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:speciesPage }

taxonomy:
    locales:  { en: "/en/marine-animals/taxonomy", pt: "/pt/animais-marinhos/taxonomia" }
    defaults: { _controller: SkaphandrusAppBundle:Default:taxonomy }

taxonomy_source:
    locales:  { en: "/en/species/source", pt: "/pt/species/source" }
    defaults: { _controller: SkaphandrusAppBundle:Default:source }

taxon:
    locales:  { en: "/en/marine-animals/{node}/{slug}", pt: "/pt/animais-marinhos/{node}/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:taxon }

business: 
    locales:  { en: "/en/scuba-diving-center/{country}/{location}/{slug}", pt: "/pt/centros-mergulho/{country}/{location}/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:business }
    
business_no_slug:
    locales:  { en: "/en/business/{id}", pt: "/pt/empresa/{id}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:business_no_slug }
    
users-home: 
    locales:  { en: "/en/users", pt: "/pt/utilizadores" }
    defaults: { _controller: SkaphandrusAppBundle:Default:usersHome }

contest_programs:
    locales:  { en: "/en/underwater-photo-contest/programs", pt: "/pt/concurso-fotografia-subaquatica/programas" }
    defaults: { _controller: SkaphandrusAppBundle:Default:contestPrograms }
    
business_programs:
    locales:  { en: "/en/scuba-diving-center/programs", pt: "/pt/centros-mergulho/programas" }
    defaults: { _controller: SkaphandrusAppBundle:Default:businessPrograms }


terms_and_conditions:
    locales:  { en: "/en/terms-and-conditions", pt: "/pt/termos-e-condicoes" }
    defaults: { _controller: SkaphandrusAppBundle:Default:terms }

################################################################################
spot:
    locales:  { en: "/en/scuba-diving-sites/spot/{country}/{location}/{slug}", pt: "/pt/spots-mergulho/spot/{country}/{location}/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:spot }

location:
    locales:  { en: "/en/scuba-diving-sites/location/{country}/{slug}", pt: "/pt/spots-mergulho/local/{country}/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:location }

country:
    locales:  { en: "/en/scuba-diving-sites/country/{slug}", pt: "/pt/spots-mergulho/pais/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:country }

locations_home:
    locales:  { en: "/en/scuba-diving-sites", pt: "/pt/spots-mergulho" }
    defaults: { _controller: SkaphandrusAppBundle:Default:locationsHome }

################################################################################

photo:
    locales:  { en: "/en/underwater-photography/photo/{id}-{slug}", pt: "/pt/fotografia-subaquatica/fotografia/{id}-{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:photo }
    
photo_no_slug:
    locales:  { en: "/en/underwater-photography/photo/{id}", pt: "/pt/fotografia-subaquatica/fotografia/{id}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:photo }

photos:
    locales:  { en: "/en/underwater-photography/photos", pt: "/pt/fotografia-subaquatica/fotografias" }
    defaults: { _controller: SkaphandrusAppBundle:Default:photos }

################################################################################
user:
    locales:  { en: "/en/users/username/{id}", pt: "/pt/utilizadores/utilizador/{id}" }
    defaults: { _controller: SkaphandrusAppBundle:Default:user }

################################################################################
search:
    locales:  { en: "/en/search-results", pt: "/pt/resultados-pesquisa" }
    defaults: { _controller: SkaphandrusAppBundle:Default:search }


#################################################################################  
#### FUN CONTESTS
#################################################################################
      
contests_landing_page:
    locales:  { en: "/en/underwater-photo-contest", pt: "/pt/concurso-fotografia-subaquatica" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:landing }

contests_photos:
    locales:  { en: "/en/underwater-photo-contest/photos/{contest_slug}/{category_slug}", pt: "/pt/concurso-fotografia-subaquatica/fotografias/{contest_slug}/{category_slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:photos }

contest_participate:
    locales:  { en: "/en/underwater-photo-contest/participate/{contest_id}", pt: "/pt/concurso-fotografia-subaquatica/participa/{contest_id}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:participate }
    
contest_add_photo:
    locales:  { en: "/en/category/{category_id}/add-photo/{photo_id}", pt: "/pt/categoria/{category_id}/adicionar-fotografia/{photo_id}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:addPhoto }

contest_remove_photo:
    locales:  { en: "/en/category/{category_id}/remove-photo/{photo_id}", pt: "/pt/category/{category_id}/remover-fotografia/{photo_id}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:removePhoto }

contest_vote_photo:
    locales:  { en: "/en/category/{category_id}/vote-photo/{photo_id}", pt: "/pt/category/{category_id}/votar-fotografia/{photo_id}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:votePhoto }

contests_photographers:
    locales:  { en: "/en/underwater-photo-contest/photographers/{contest_slug}", pt: "/pt/concurso-fotografia-subaquatica/fotografos/{contest_slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:photographers }

contests_sponsors:
    locales:  { en: "/en/underwater-photo-contest/sponsors/{contest_slug}", pt: "/pt/concurso-fotografia-subaquatica/patrocinadores/{contest_slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:sponsors }

contests_winners:
    locales:  { en: "/en/underwater-photo-contest/winners/{contest_slug}", pt: "/pt/concurso-fotografia-subaquatica/vencedores/{contest_slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:winners }

contests_contest:
    locales:  { en: "/en/underwater-photo-contest/{slug}", pt: "/pt/concurso-fotografia-subaquatica/{slug}" }
    defaults: { _controller: SkaphandrusAppBundle:Contest:contest }



