skaphandrus_app_photo_admin:
    resource: "@SkaphandrusAppBundle/Resources/config/routing/skphoto.yml"
    prefix:   /photo_admin

skaphandrus_app_hello:
    path:     /hello/{name}
    defaults: { _controller: SkaphandrusAppBundle:Default:hello }

skaphandrus_app_users_migration:
    path:     /migration/migration
    defaults: { _controller: SkaphandrusAppBundle:Default:usersMigration }
    
################################################################################  
### TRANSVERSAL
################################################################################    
    
#CONTROLLER DEFAULT    
#homepage_index:
#    path:     /index
#    defaults: { _controller: SkaphandrusAppBundle:Default:index }    
#

index:
    path:      /{_locale}/index
    defaults:  { _controller: SkaphandrusAppBundle:Default:index, _locale: en }
    requirements:
        _locale:  en|fr

index2:
    path:      /{_locale}/index2
    defaults:  { _controller: SkaphandrusAppBundle:Default:index2, _locale: en }
    requirements:
        _locale:  en|fr

##CONTROLLER SPECIES
species:
    path:     /{_locale}/marine-species/info/species/{slug}
    defaults: { _controller: SkaphandrusAppBundle:Species:speciesPage, _locale: en }
    requirements:
        _locale:  en|pt

taxon:
    path:     /{_locale}/marine-species/{node}/{slug}
    defaults: { _controller: SkaphandrusAppBundle:Species:taxon, _locale: en }
    requirements:
        _locale:  en|pt

spot:
    path:     /{_locale}/scuba-dive-locations/info/spot/{country}/{location}/{slug}
    defaults: { _controller: SkaphandrusAppBundle:Species:spot, _locale: en }
    requirements:
        _locale:  en|pt

#
#

#kingdom:
#  url:   /:sf_culture/marine-species/kingdom/:slug/*
#  param: { module: kingdom, action: index }
#  
#phylum:
#  url:   /:sf_culture/marine-species/phylum/:slug/*
#  param: { module: phylum, action: index }
#
#class:
#  url:   /:sf_culture/marine-species/class/:slug/*
#  param: { module: class, action: index }
#
#order:
#  url:   /:sf_culture/marine-species/order/:slug/*
#  param: { module: order, action: index }
#
#family:
#  url:   /:sf_culture/marine-species/family/:slug/*
#  param: { module: family, action: index }
#  
#genus:
#  url:   /:sf_culture/marine-species/genus/:slug/*
#  param: { module: genus, action: index }
#
#
#species:
#  url:   /:sf_culture/marine-species/info/species/:slug/*
#  param: { module: species, action: speciesInfo }
#
#
#
#
#
#
#
#
#################################################################################  
#### FUN CONTESTS
#################################################################################
# 
#contest_involved:
#  url:   /:sf_culture/underwater-photo-contest/involved/:slug/*
#  param: { module: photoContest, action: contestInvolved }
#
##contest_photos:
##  url:   /:sf_culture/underwater-photo-contest/photos/:slug/*
##  param: { module: photoContest, action: contestPhotos }
#
#contest_category:
#  url:   /:sf_culture/underwater-photo-contest/photos/:slug/:category
#  param: { module: photoContest, action: contestPhotosCategory }
#
#contest_photographers:
#  url:   /:sf_culture/underwater-photo-contest/photographers/:slug/*
#  param: { module: photoContest, action: contestPhotographers }
#
#contest_sponsors:
#  url:   /:sf_culture/underwater-photo-contest/sponsors/:slug/*
#  param: { module: photoContest, action: contestSponsors }
#
#contest_about:
#  url:   /:sf_culture/underwater-photo-contest/about/:slug/*
#  param: { module: photoContest, action: contestAbout }
#
#contest_results:
#  url:   /:sf_culture/underwater-photo-contest/results/:slug/*
#  param: { module: photoContest, action: contestResults }
#
#contest_home:
#  url:   /:sf_culture/underwater-photo-contest/:slug/*
#  param: { module: photoContest, action: contestHome }
#
#
#
#
################################################################################
#### APP OCEAN LIFE ID
################################################################################
#
#identification_criterias:
#  url:   /:sf_culture/app/criterias.:sf_format
#  param: { module: identification, action: jsonCriteriasList}
#  requirements:
#    sf_method: [post,put]
#    sf_format: (?:xml|json)
#
#identification_species:
#  url:   /:sf_culture/app/species.:sf_format
#  param: { module: identification, action: jsonSpeciesList}
#  requirements:
#    sf_method: [post,put]
#    sf_format: (?:xml|json)
#
#identification_modules:
#  url:   /:sf_culture/app/modules.:sf_format
#  param: { module: identification, action: jsonModulesList}
#  requirements:
#    sf_method: [post,put]
#    sf_format: (?:xml|json)
#
#identification_species_info:
#  url:   /:sf_culture/app/speciesinfo.:sf_format
#  param: { module: identification, action: jsonSpeciesInfo}
#  requirements:
#    sf_method: [post,put]
#    sf_format: (?:xml|json)
#    
#identification_taxons:
#  url:   /:sf_culture/app/taxons.:sf_format
#  param: { module: identification, action: jsonTaxonsList}
#  requirements:
#    sf_method: [post,put]
#    sf_format: (?:xml|json)
#    
#identification_array:
#  url:   /:sf_culture/app/array.:sf_format
#  param: { module: identification, action: jsonArray}
#  requirements:
#    sf_method: [post,put]
#    sf_format: (?:xml|json)    
#
#
#


