services:
#    skaphandrus_app.example:
#        class: Skaphandrus\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    utils.twig_extension:
        class: Skaphandrus\AppBundle\Twig\UtilsExtension
        public: false
        arguments: ["@service_container", "@translator.default"]
        tags:
            - { name: twig.extension }

    twig.extension.Date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    skaphandrus_user.registration.form.type:
        class: Skaphandrus\AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: skaphandrus_user_registration }

    skaphandrus_user.resetting.form.type:
        class: Skaphandrus\AppBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: skaphandrus_user_resetting }

    skaphandrus_message.new_thread.form.type:
        class: Skaphandrus\AppBundle\Form\FOSMessage\NewThreadMessageFormType
        tags:
            - { name: form.type, alias: skaphandrus_message_new_thread }
