services:
#    skaphandrus_app.example:
#        class: Skaphandrus\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    utils.twig_extension:
        class: Skaphandrus\AppBundle\Twig\UtilsExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
    skaphandrus_user.registration.form.type:
        class: Skaphandrus\AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: skaphandrus_user_registration }
